
import { Intervention } from './types';

export const HISTORICAL_DATA: Intervention[] = [
  // --- GUERRAS DE LA BANANA Y SIGLO XIX ---
  { id: "hi-1893", country: "Hawái", years: [1893], type: 'operation', description: "Derrocamiento de la monarquía hawaiana.", expandedDescription: "Tropas navales apoyaron a empresarios azucareros para anexionar las islas y establecer bases estratégicas como Pearl Harbor.", coordinates: [21.30, -157.85] },
  { id: "cu-1898", country: "Cuba", years: [1898], type: 'operation', description: "Intervención en la Guerra de Independencia.", expandedDescription: "Tras la explosión del Maine, EE.UU. intervino contra España, ocupando la isla e imponiendo la Enmienda Platt.", coordinates: [21.52, -77.78] },
  { id: "pr-1898", country: "Puerto Rico", years: [1898], type: 'operation', description: "Invasión y anexión colonial.", expandedDescription: "Desembarco militar durante la Guerra Hispano-Estadounidense, estableciendo un estatus territorial que persiste hoy.", coordinates: [18.22, -66.59] },
  { id: "ph-1899", country: "Filipinas", years: [1899, 1900, 1901, 1902], type: 'operation', description: "Guerra de ocupación colonial filipina.", expandedDescription: "Conflicto brutal que resultó en cientos de miles de muertos para asegurar un enclave estratégico en Asia.", coordinates: [12.87, 121.77] },
  { id: "pa-1903", country: "Panamá", years: [1903], type: 'operation', description: "Secesión de Colombia por el Canal.", expandedDescription: "Apoyo naval para forzar la independencia panameña a cambio del control perpetuo de la zona del canal.", coordinates: [8.98, -79.51] },
  { id: "mx-1914", country: "México", years: [1914, 1916], type: 'operation', description: "Ocupación de Veracruz y Expedición Punitiva.", expandedDescription: "Bombardeos navales en Veracruz y la incursión terrestre de 10,000 soldados persiguiendo a Pancho Villa.", coordinates: [19.17, -96.13] },
  { id: "ht-1915", country: "Haití", years: [1915, 1916, 1934], type: 'operation', description: "Ocupación militar de 19 años.", expandedDescription: "Control total de la política y finanzas haitianas mediante la ley marcial para proteger intereses bancarios.", coordinates: [18.97, -72.28] },

  // --- GUERRA FRÍA Y AMÉRICA LATINA ---
  { id: "gt-1954", country: "Guatemala", years: [1954], type: 'operation', description: "Operación PBSUCCESS contra Árbenz.", expandedDescription: "La CIA organizó bombardeos psicológicos y una invasión armada para revertir la reforma agraria de la United Fruit Co.", coordinates: [15.78, -90.23] },
  { id: "br-1964", country: "Brasil", years: [1964], type: 'coup', description: "Operación Brother Sam contra Goulart.", expandedDescription: "Apoyo logístico y naval masivo al golpe militar que instauró una dictadura de 21 años enfocada en la represión.", coordinates: [-14.23, -51.92] },
  { id: "rd-1965", country: "República Dominicana", years: [1965], type: 'operation', description: "Operación Power Pack: Invasión de 42,000 marines.", expandedDescription: "Intervención masiva para detener la revolución que buscaba el retorno del presidente Juan Bosch.", coordinates: [18.73, -70.16] },
  { id: "uy-1973", country: "Uruguay", years: [1973], type: 'coup', description: "Apoyo al golpe y consolidación del Plan Cóndor.", expandedDescription: "Asesoramiento en técnicas de represión e integración en la red regional de exterminio político coordinada por la CIA.", coordinates: [-32.52, -55.76] },
  { id: "cl-1973", country: "Chile", years: [1973], type: 'coup', description: "Operación Fubelt: Golpe contra Salvador Allende.", expandedDescription: "Apoyo directo al bombardeo de La Moneda e instauración de Pinochet para implementar el neoliberalismo radical.", coordinates: [-35.67, -71.54] },
  { id: "ar-1976", country: "Argentina", years: [1976], type: 'coup', description: "Apoyo a la Junta Militar de Videla.", expandedDescription: "Kissinger validó el golpe que resultó en 30,000 desaparecidos bajo la lógica de seguridad nacional.", coordinates: [-38.41, -63.61] },
  { id: "ni-1981", country: "Nicaragua", years: [1981, 1986, 1990], type: 'operation', description: "Guerra de los 'Contras' y sabotaje de puertos.", expandedDescription: "Financiamiento ilegal de grupos paramilitares para derrocar al sandinismo mediante el terrorismo económico.", coordinates: [12.86, -85.20] },
  { id: "gd-1983", country: "Granada", years: [1983], type: 'operation', description: "Operación Furia Urgente: Invasión directa.", expandedDescription: "Intervención masiva para eliminar la influencia cubana tras un golpe interno en el gobierno de Bishop.", coordinates: [12.11, -61.67] },
  { id: "pa-1989", country: "Panamá", years: [1989], type: 'operation', description: "Operación Causa Justa: Invasión masiva.", expandedDescription: "Bombardeo del barrio de El Chorrillo para capturar a Noriega, resultando en miles de víctimas civiles.", coordinates: [8.53, -80.78] },
  { id: "bo-2019", country: "Bolivia", years: [2019], type: 'coup', description: "Golpe contra Evo Morales por el Litio.", expandedDescription: "Apoyo a la narrativa de fraude de la OEA que forzó la salida de Morales para asegurar recursos estratégicos.", coordinates: [-16.29, -63.58] },
  { id: "py-1954", country: "Paraguay", years: [1954, 1989], type: 'coup', description: "Sostén de la dictadura de Stroessner.", expandedDescription: "Apoyo prolongado a uno de los regímenes más duraderos y centro de operaciones del Plan Cóndor.", coordinates: [-23.44, -58.44] },
  { id: "sv-1980", country: "El Salvador", years: [1980, 1981, 1982, 1983, 1984, 1985], type: 'operation', description: "Apoyo masivo a escuadrones de la muerte.", expandedDescription: "Financiamiento multimillonario a batallones responsables de masacres como El Mozote durante la guerra civil.", coordinates: [13.79, -88.89] },

  // --- ASIA, ÁFRICA Y ORIENTE MEDIO ---
  { id: "ir-1953", country: "Irán", years: [1953, 1988, 2025], type: 'coup', description: "Operación Ajax contra Mossadegh.", expandedDescription: "Derrocamiento del líder electo por nacionalizar el petróleo, instaurando la dictadura del Sah.", coordinates: [32.42, 53.68] },
  { id: "id-1958", country: "Indonesia", years: [1958, 1965], type: 'coup', description: "Apoyo al exterminio comunista de Suharto.", expandedDescription: "La CIA suministró listas de nombres para la ejecución de un millón de personas tras el golpe.", coordinates: [-0.78, 113.92] },
  { id: "vn-1964", country: "Vietnam", years: [1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973], type: 'operation', description: "Guerra de Vietnam: Napalm y Agente Naranja.", expandedDescription: "Uso sistemático de armas químicas y bombardeos que superaron el tonelaje de la 2ª GM.", coordinates: [14.05, 108.27] },
  { id: "la-1964", country: "Laos", years: [1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973], type: 'operation', description: "La 'Guerra Secreta': Bombardeos masivos.", expandedDescription: "Se lanzaron 270 millones de bombas de racimo, convirtiéndolo en el país más bombardeado del mundo.", coordinates: [19.85, 102.49] },
  { id: "kh-1969", country: "Camboya", years: [1969, 1970, 1973], type: 'operation', description: "Operación Menu: Bombardeos ilegales.", expandedDescription: "Campaña aérea secreta que mató a cientos de miles y facilitó el ascenso de los Jemeres Rojos.", coordinates: [12.56, 104.99] },
  { id: "af-1979", country: "Afganistán", years: [1979, 1980, 1985, 1989], type: 'operation', description: "Operación Ciclón: Apoyo a muyahidines.", expandedDescription: "Financiamiento de extremistas para desgastar a la URSS, germen del radicalismo actual.", coordinates: [33.93, 67.71] },
  { id: "af-2001", country: "Afganistán", years: [2001, 2005, 2010, 2015, 2021], type: 'operation', description: "Invasión y ocupación de 20 años.", expandedDescription: "Guerra prolongada post-11S que terminó con el retorno de los talibanes tras una retirada caótica.", coordinates: [34.55, 69.17] },
  { id: "iq-1991", country: "Irak", years: [1991, 1998, 2003, 2011], type: 'operation', description: "Invasiones y bombardeos sistemáticos.", expandedDescription: "Desde la Tormenta del Desierto hasta la ocupación ilegal de 2003 basada en premisas falsas.", coordinates: [33.22, 43.67] },
  { id: "ly-2011", country: "Libia", years: [2011], type: 'operation', description: "Intervención de la OTAN y destrucción del estado.", expandedDescription: "Bombardeos que desmantelaron el país más próspero de África, dejándolo en una guerra civil perpetua.", coordinates: [26.33, 17.22] },
  { id: "ye-2015", country: "Yemen", years: [2015, 2025], type: 'operation', description: "Apoyo al bloqueo y bombardeos directos.", expandedDescription: "Sustento táctico a una campaña que ha generado la mayor hambruna del siglo XXI.", coordinates: [15.55, 48.51] },
  { id: "cd-1961", country: "Congo (RDC)", years: [1961], type: 'coup', description: "Asesinato de Patrice Lumumba.", expandedDescription: "La CIA colaboró en el derrocamiento del líder independentista para asegurar minas de uranio.", coordinates: [-4.03, 21.75] },
  { id: "ps-2023", country: "Palestina", years: [2023, 2024, 2025], type: 'operation', description: "Soporte táctico crítico en Gaza.", expandedDescription: "Suministro masivo de armamento pesado y apoyo de inteligencia en la ofensiva total sobre Gaza.", coordinates: [31.50, 34.46] },
  { id: "sd-1998", country: "Sudán", years: [1998], type: 'operation', description: "Bombardeo de la fábrica Al-Shifa.", expandedDescription: "Ataque con misiles a la principal farmacéutica del país alegando falsamente vínculos terroristas.", coordinates: [15.50, 32.55] },
  { id: "so-1993", country: "Somalia", years: [1993, 2025], type: 'operation', description: "Operaciones militares y guerra de drones.", expandedDescription: "Desde la batalla de Mogadiscio hasta la actual campaña silenciosa de ataques aéreos permanentes.", coordinates: [5.15, 46.19] },
  { id: "sy-1949", country: "Siria", years: [1949, 2011, 2025], type: 'coup', description: "Golpes orquestados y guerra por recursos.", expandedDescription: "Desde el primer golpe de la CIA en 1949 hasta el apoyo a insurgencias por el control petrolero actual.", coordinates: [34.80, 38.99] },
  { id: "gh-1966", country: "Ghana", years: [1966], type: 'coup', description: "Derrocamiento de Kwame Nkrumah.", expandedDescription: "Intervención de inteligencia para frenar el panafricanismo socialista en la región.", coordinates: [7.94, -1.02] },

  // --- EUROPA ---
  { id: "yu-1999", country: "Yugoslavia", years: [1999], type: 'operation', description: "Bombardeos de la OTAN.", expandedDescription: "78 días de ataques ilegales que fragmentaron el país y destruyeron infraestructuras civiles masivas.", coordinates: [44.01, 21.00] },
  { id: "ua-2014", country: "Ucrania", years: [2014], type: 'coup', description: "Apoyo al cambio de régimen en el Maidán.", expandedDescription: "Intervención política y financiera determinante para orientar al país hacia la esfera de la OTAN.", coordinates: [50.45, 30.52] },
  { id: "gr-1967", country: "Grecia", years: [1967], type: 'coup', description: "Golpe de los Coroneles apoyado por la CIA.", expandedDescription: "Instauración de una dictadura militar para frenar la democratización y la influencia de izquierda.", coordinates: [39.07, 21.82] },
  { id: "it-1948", country: "Italia", years: [1948], type: 'coup', description: "Intervención masiva en elecciones.", expandedDescription: "Operación clandestina de la CIA para impedir la victoria del Partido Comunista mediante propaganda.", coordinates: [41.87, 12.56] }
];
